import assert from 'node:assert/strict';
import { test } from 'node:test';
import { LlmClient, LlmMessage, Tool, ToolCall } from '../src/types.js';
import { makeEngine, StubMcp } from './helpers/copilotTestUtils.js';

// Test removed: LLMs no longer return or manage chatId

test('executes LLM-planned tool calls', async () => {
  const llm: LlmClient = {
    async chat(messages: LlmMessage[], tools: Tool[]) {
      if (tools.length) {
        return {
          content: 'plan',
          toolCalls: [{ name: 'query-services', arguments: {} }],
        };
      }
      return {
        content: JSON.stringify({ conclusion: 'services healthy', evidence: ['services list ok'], confidence: 0.95 }),
        toolCalls: [],
      };
    },
  };

  const mcp: StubMcp = {
    async listTools() {
      return [{ name: 'query-services' } as Tool];
    },
    async callTool(call) {
      assert.equal(call.name, 'query-services');
      return { name: call.name, result: { services: ['checkout'] } };
    },
  };

  const engine = makeEngine(llm, mcp);
  const answer = await engine.answer('List services');

  // Engine generates and owns chatId - just verify it exists
  assert.ok(answer.chatId, 'Answer should have a chatId generated by engine');
  assert.ok(answer.conclusion.includes('services'));
  assert.ok(answer.evidence && answer.evidence.length > 0);
});

test('extracts incident references from MCP text content payloads', async () => {
  const llm: LlmClient = {
    async chat(messages: LlmMessage[], tools: Tool[]) {
      if (tools.length) {
        return {
          content: 'plan',
          toolCalls: [{ name: 'query-incidents', arguments: { service: 'payments' } }],
          chatId: 'conv-incidents-plan',
        };
      }
      return {
        content: JSON.stringify({ conclusion: 'done', evidence: [] }),
        toolCalls: [],
        chatId: 'conv-incidents-plan',
      };
    },
  };

  const incidents = [
    {
      id: 'inc-003',
      title: 'Payments webhook timeouts from Stripe',
      severity: 'sev1',
      status: 'open',
    },
  ];

  const mcp: StubMcp = {
    async listTools() {
      return [{ name: 'query-incidents' } as Tool];
    },
    async callTool(call) {
      return {
        name: call.name,
        result: {
          content: [
            {
              type: 'text',
              text: JSON.stringify(incidents, null, 2),
            },
          ],
        },
      };
    },
  };

  const engine = makeEngine(llm, mcp);
  const answer = await engine.answer('show incidents');
  assert.deepEqual(answer.references?.incidents, ['inc-003']);
});

// Test removed: LLMs no longer manage chatId - the engine now generates and controls conversation IDs

test('falls back to heuristic plan when LLM fails', async () => {
  const llm: LlmClient = {
    async chat(_messages: LlmMessage[] = [], _tools: Tool[] = [], _opts?: { chatId?: string }) {
      throw new Error('llm-fail');
    },
  };

  const calls: ToolCall[] = [];
  const mcp: StubMcp = {
    async listTools() {
      return [{ name: 'query-incidents' } as Tool];
    },
    async callTool(call) {
      calls.push(call);
      return { name: call.name, result: { ok: true } };
    },
  };

  const engine = makeEngine(llm, mcp);
  const answer = await engine.answer('Find impactful incidents');
  assert.ok(answer.conclusion.length > 0);
  assert.equal(calls[0]?.name, 'query-incidents');
});

test('asks LLM for explicit JSON plan when no tool calls were returned', async () => {
  const toolUsages: number[] = [];
  const llm: LlmClient = {
    async chat(messages: LlmMessage[], tools: Tool[], _opts?: { chatId?: string }) {
      toolUsages.push(tools.length);

      // 1. Initial Plan (tools provided)
      if (toolUsages.length === 1) {
        return { content: 'no tool calls', toolCalls: [], chatId: 'conv-json-plan' };
      }

      // 2. JSON Plan (no tools provided)
      if (toolUsages.length === 2) {
        const lastSystem = messages.find((m) => m.role === 'system');
        assert.ok(lastSystem && lastSystem.content?.includes('JSON'), 'planner system prompt should request JSON');
        return {
          content: JSON.stringify({ toolCalls: [{ name: 'query-services', arguments: {} }] }),
          toolCalls: [],
          chatId: 'conv-json-plan',
        };
      }

      // 3. Follow-up Plan (tools provided)
      if (toolUsages.length === 3) {
        return { content: 'no follow ups', toolCalls: [], chatId: 'conv-json-plan' };
      }

      // 4. Synthesis (no tools provided)
      return {
        content: JSON.stringify({ conclusion: 'Mock conclusion' }),
        toolCalls: [],
        chatId: 'conv-json-plan',
      };
    },
  };

  const calls: ToolCall[] = [];
  const mcp: StubMcp = {
    async listTools() {
      return [{ name: 'query-services' } as Tool];
    },
    async callTool(call) {
      calls.push(call);
      return { name: call.name, result: { ok: true } };
    },
  };

  const engine = makeEngine(llm, mcp);
  const answer = await engine.answer('What can you see?');
  assert.deepEqual(toolUsages.slice(0, 2), [1, 0]);
  assert.equal(calls[0]?.name, 'query-services');
  assert.equal(answer.conclusion, 'Mock conclusion');
});

test('executes multi-step reasoning loop', async (t) => {
  // MockLlm and CopilotEngine are not defined in this file, assuming they are imported or defined elsewhere for this test.
  // For the purpose of this edit, I'll use the existing LlmClient and makeEngine helpers.
  // If MockLlm and CopilotEngine are truly new, they would need to be defined or imported.
  // Given the context, I'll adapt to use existing helpers.

  const llm: LlmClient = {
    async chat(messages: LlmMessage[], tools: Tool[]) {
      const lastMessage = messages[messages.length - 1];
      if (lastMessage.content === 'investigate steps') { // Initial plan
        return { content: '', toolCalls: [{ name: 'step1', arguments: {} }] };
      }
      // Subsequent plans based on tool results
      // The planner puts tool results in the user message
      if (lastMessage.role === 'user' && lastMessage.content?.includes('step2') && !lastMessage.content?.includes('done: true')) {
        return { content: '', toolCalls: [{ name: 'step2', arguments: {} }] };
      }
      if (lastMessage.role === 'user' && lastMessage.content?.includes('done: true')) {
        return { content: 'Conclusion', toolCalls: [] };
      }
      return { content: 'Fallback conclusion', toolCalls: [] };
    },
  };

  const calls: ToolCall[] = [];
  const mcp: StubMcp = {
    async listTools() {
      return [
        { name: 'step1', inputSchema: { type: 'object' } } as Tool,
        { name: 'step2' } as Tool
      ];
    },
    async callTool(call): Promise<any> {
      calls.push(call);
      if (call.name === 'step1') return { name: 'step1', result: { next: 'step2' } };
      if (call.name === 'step2') return { name: 'step2', result: { done: true } };
      return { name: 'unknown', result: null };
    },
  };

  const engine = makeEngine(llm, mcp, { maxIterations: 3 }); // Assuming makeEngine can take maxIterations
  await engine.answer('investigate steps');

  // Should have called tools 2 times (step1, then step2)
  assert.equal(calls.length, 2);
  assert.deepEqual(calls.map(c => c.name), ['step1', 'step2']);
});

test('stops loop when max iterations reached', async () => {
  let llmCallCount = 0;
  const llmLoop: LlmClient = {
    async chat(_messages: LlmMessage[], _tools: Tool[]) {
      llmCallCount++;
      // LLM always returns a tool call, trying to loop forever
      // Use unique args to bypass cache
      return {
        content: '',
        toolCalls: [{ name: 'loop', arguments: { i: Math.random() } }]
      };
    },
  };

  let toolCallCount = 0;
  const mcpLoop: StubMcp = {
    async listTools() {
      return [{ name: 'loop', inputSchema: {} } as Tool];
    },
    async callTool(_call) {
      toolCallCount++;
      return { name: 'loop', result: 'ok' };
    },
  };

  const engineLoop = makeEngine(llmLoop, mcpLoop, { maxIterations: 2 });

  await engineLoop.answer('investigate loop');

  // Should stop after 2 iterations
  assert.equal(toolCallCount, 2, `Expected 2 tool calls but got ${toolCallCount}`);
});

test('skips placeholder args and reports missing data', async () => {
  const llm: LlmClient = {
    async chat(_messages: LlmMessage[] = [], _tools: Tool[] = [], _opts?: { chatId?: string }) {
      return {
        content: 'plan',
        toolCalls: [{ name: 'get-incident-timeline', arguments: { id: '{{incidentId}}' } }],
        chatId: 'conv-placeholder-plan',
      };
    },
  };

  const mcp: StubMcp = {
    async listTools() {
      return [{ name: 'get-incident-timeline' } as Tool];
    },
    async callTool() {
      throw new Error('should not be called');
    },
  };

  const engine = makeEngine(llm, mcp);
  const answer = await engine.answer('What triggered severity change?');
  assert.ok(answer.missing?.includes('tool outputs'));
});

test('caps planner to 3 tool calls per iteration even if LLM proposes more', async () => {
  let plannerCalls = 0;
  const llm: LlmClient = {
    async chat(_messages: LlmMessage[], tools: Tool[], _opts?: { chatId?: string }) {
      if (tools.length) {
        plannerCalls += 1;
        if (plannerCalls === 1) {
          return {
            content: 'plan',
            toolCalls: [
              { name: 'a', arguments: {} },
              { name: 'b', arguments: {} },
              { name: 'c', arguments: {} },
              { name: 'd', arguments: {} },
            ],
            chatId: 'conv-capped-plan',
          };
        }
        return { content: 'no follow ups', toolCalls: [], chatId: 'conv-capped-plan' };
      }
      return {
        content: JSON.stringify({ conclusion: 'done', evidence: [] }),
        toolCalls: [],
        chatId: 'conv-capped-plan',
      };
    },
  };

  const calls: ToolCall[] = [];
  const mcp: StubMcp = {
    async listTools() {
      return [
        { name: 'a' } as Tool,
        { name: 'b' } as Tool,
        { name: 'c' } as Tool,
        { name: 'd' } as Tool,
      ];
    },
    async callTool(call) {
      calls.push(call);
      return { name: call.name, result: { ok: true } };
    },
  };

  const engine = makeEngine(llm, mcp);
  await engine.answer('Need many tools');
  assert.equal(calls.length, 3);
  assert.deepEqual(
    calls.map((call) => call.name),
    ['a', 'b', 'c'],
    'engine should execute only the first 3 tool calls'
  );
});

test('skips tool calls missing MCP-required fields', async () => {
  const llm: LlmClient = {
    async chat(_messages: LlmMessage[] = [], _tools: Tool[] = [], _opts?: { chatId?: string }) {
      return {
        content: 'plan',
        toolCalls: [
          { name: 'query-metrics', arguments: { start: '2024-01-01T00:00:00Z', end: '2024-01-01T01:00:00Z' } },
        ],
        chatId: 'conv-missing-fields',
      };
    },
  };

  const calls: ToolCall[] = [];
  const mcp: StubMcp = {
    async listTools() {
      return [
        {
          name: 'query-metrics',
          inputSchema: {
            type: 'object',
            required: ['expression', 'step', 'start', 'end'],
            properties: {
              expression: { type: 'string' },
              step: { type: 'integer' },
              start: { type: 'string' },
              end: { type: 'string' },
            },
          },
        } as Tool,
      ];
    },
    async callTool(call) {
      calls.push(call);
      return { name: call.name, result: { ok: true } };
    },
  };

  const engine = makeEngine(llm, mcp);
  const answer = await engine.answer('check metrics');
  assert.equal(calls.length, 0, 'call should be skipped because required fields are missing');
  assert.ok(answer.conclusion.includes('No tool results'), 'answer should reflect missing tool outputs');
});

test('defers to LLM plan even when heuristics might inject', async () => {
  const llm: LlmClient = {
    async chat(_messages: LlmMessage[] = [], tools: Tool[] = [], _opts?: { chatId?: string }) {
      if (tools.length) {
        // LLM provides a valid plan (health check)
        return { content: 'plan', toolCalls: [{ name: 'health', arguments: {} }], chatId: 'conv-defer-plan' };
      }
      return { content: JSON.stringify({ conclusion: 'done' }), toolCalls: [], chatId: 'conv-defer-plan' };
    },
  };

  const calls: ToolCall[] = [];
  const mcp: StubMcp = {
    async listTools() {
      return [{ name: 'health' } as Tool, { name: 'query-incidents' } as Tool];
    },
    async callTool(call) {
      calls.push(call);
      return { name: call.name, result: { ok: true } };
    },
  };

  const engine = makeEngine(llm, mcp);
  await engine.answer('Summarize the latest SEV1 incident');

  // With conservative heuristics, we trust the LLM's plan
  // Even though question mentions SEV1, heuristics defer to LLM choice
  assert.equal(calls.length, 1);
  assert.equal(calls[0]?.name, 'health', 'Should execute LLM\'s chosen tool');
});

test('adds default logs and metrics calls when user explicitly asks for them', async () => {
  const llm: LlmClient = {
    async chat(_messages: LlmMessage[] = [], tools: Tool[] = [], _opts?: { chatId?: string }) {
      if (tools.length) {
        return { content: 'plan', toolCalls: [], chatId: 'conv-default-logs' };
      }
      return { content: JSON.stringify({ conclusion: 'done' }), toolCalls: [], chatId: 'conv-default-logs' };
    },
  };

  const calls: ToolCall[] = [];
  const mcp: StubMcp = {
    async listTools() {
      return [{ name: 'query-logs' } as Tool, { name: 'query-metrics' } as Tool];
    },
    async callTool(call) {
      calls.push(call);
      return { name: call.name, result: { ok: true } };
    },
  };

  const engine = makeEngine(llm, mcp);
  await engine.answer('Tell me more about 504s in logs and metrics');

  assert.equal(calls.length, 2);
  assert.equal(calls[0]?.name, 'query-logs');
  assert.ok(((calls[0]?.arguments as any).query as string).includes('504'));
  assert.ok(typeof (calls[0]?.arguments as any).start === 'string');
  assert.equal(calls[1]?.name, 'query-metrics');
  assert.equal((calls[1]?.arguments as any).step, 60);
});
